### ISSUE TITLE
Dataloaders for ECL and Weather

### ISSUE THREAD

**Issue by JBurchert** [zhouhaoyi/Informer2020#73] opened 2021-03-26 13:34 UTC
Hello everyone,
first of all, thank you for your amazing paper! 
We are currently trying to reproduce your results and want to run the experiments on the weather and ECL datasets. Would it be possible for you to also publish the two data loaders you used for those particular datasets to keep the preprocessing consistent. 
Thanks a lot in advance!

**Comment by zhouhaoyi** [comment] 2021-03-27 00:54
Thanks for your attention to this work!
Since we have provided the customized data loader in the colab examples, it should be enough for guys in reproducing our results. Besides, we also keep the same preprocessing trick as the original data provider. We think it may be inappropriate to provide these datasets and data loaders through us. I hope you could understand.

**Comment by zhouhaoyi** [comment] 2021-03-28 03:58
If you do have problems with these data loaders, you can contact us through email. And I will close this issue now.

**Closed by zhouhaoyi** 2021-03-28 03:58 UTC
Labels: documentation
