### ISSUE TITLE
About the inconsistance of  ProbSparse self-attention implementation

### ISSUE THREAD

**Issue by XLechter** [zhouhaoyi/Informer2020#35] opened 2021-02-24 09:25 UTC
![image](https://user-images.githubusercontent.com/41005111/108978232-5b28cc00-76c4-11eb-80cc-a446f0056854.png)
Thanks for your great work first.

I find in the code att.py line 111:
scores_top, index = self._prob_QK(queries, keys, u, U)
it seems that U is set to n_top and it should be u in the paper?

and U is set to c*ln(n) instead of m*ln(n) in line 108:
U = self.factor * np.ceil(np.log(S)).astype('int').item()

I don't know if I misunderstand this and hope for your reply.

**Comment by zhouhaoyi** [comment] 2021-02-26 01:46
Thanks for your correction. We have noticed this issue and it may be caused by the reproducing repo from the experimental code during the paper submission. We will update a hot-fix soon.

**Comment by cookieminions** [comment] 2021-02-26 06:06
Thanks for your attention to our work. We have checked the code, and the U in the paper is not the same with the `U` in `models/attn.py`, the real U in paper corresponds to line 54 `index_sample = torch.randint(L_K, (L_Q, sample_k))` in code `models/attn.py` (the same line in old version code). And we update the code to replace `L` and `S` with `L_K` and `L_Q`, and add new comments for better reading.

**Comment by cookieminions** [comment] 2021-02-26 06:08
Setting u to n_top is correct, and that is our mistake, thanks for your correction.

**Comment by zhouhaoyi** [comment] 2021-02-28 11:00
Suppose there is no more discussion and I will close this issue in 12h.

**Comment by XLechter** [comment] 2021-02-28 11:07
Thank you for replying. It solves my problem.

**Closed** 2021-02-28 14:20 UTC
Labels: bug
